config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items
  resources :carts

  get 'home/index'

  get 'gallery/index'
  resources :stores
  devise_for :users
  
  get 'admin/login'
  post 'admin/login'
  
  get 'admin/logout'
  
  get 'account/login'
  post 'account/login'

  get "gallery/index"
  post 'gallery/index'

  get 'gallery/checkout'
  post "gallery/checkout"

  get 'gallery/purchase_complete'
  post 'gallery/purchase_complete'

  get 'gallery/search'
  post 'gallery/search'

  root 'gallery#index'
end

app/models/store.rb
class Store < ApplicationRecord
    has_many_attached :files 
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :admin_logged_in?
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end


    def admin_logged_in?
    if session[:admin].nil?
      flash[:notice] = "You need to be logged in as Admin to continue!"
      redirect_to admin_login_url
    end
  end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:model, :colour, :display, :category, :price, files: [])
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :display %>
    <%= form.text_field :display %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

    <div class="field">
      <%= form.label :files %>
      <%= form.file_field :files, multiple: true %>
  </div>


    <div class="field">
    <strong>Picture:</strong>
    <% @store.files.each do |file| %>
    <%= image_tag file, width:"100px"%>
    <% end %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="/assets/fevicon/fevicon.png" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>The TimeSquare</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

  <!-- font awesome style -->
  <link href="css/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="css/responsive.css" rel="stylesheet" />

</head>

<body>

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="index.html">
            <span>
              The TimeSquare
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item active">
                <a class="nav-link" href="/home/index"">Home <span class="sr-only">(current)</span></a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="/users/sign_in"> Sign In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/users/sign_up">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/admin/login">Admin Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/gallery/index">Gallery</a>
              </li>
            </ul>
            
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
    <!-- slider section -->
    <section class="slider_section ">
      <div class="slider_bg_box">
        <img src="/assets/slider-bg.jpg" alt="">
      </div>
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container ">
              <div class="row">
                <div class="col-md-7">
                  <div class="detail-box">
                    <h1>
                      Stylish Watches
                    </h1>
                    <p>
                     <strong><h4><em>Pick Your Style Today!</em></strong></h4>
                    </p>
                    
                  </div>
                </div>
              </div>
            </div>
          </div>  
    </section>
  </div>


<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Colour</th>
      <th>Display</th>
      <th>Category</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.model %></td>
        <td><%= store.colour %></td>
        <td><%= store.display %></td>
        <td><%= store.category %></td>
        <td><%= store.price %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

<br>
 <section class="info_section layout_padding2">
    <div class="container">
    <div style="text-align: center;">
        
        <h2 > &copy; The TimeSquare</h2></p>
        
    </div>
    </div>
  </section>

</body>
</html>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @store.model %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @store.colour %>
</p>

<p>
  <strong>Display:</strong>
  <%= @store.display %>
</p>

<p>
  <strong>Category:</strong>
  <%= @store.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @store.price %>
</p>

<!-- 
  <% @store.files.each do |file| %>
   <%= link_to file.filename, rails_blob_path(file, disposition: :attachment) %>
 <% end %>
-->

   <% if @store.files.any? %>
   <p><strong>Picture:</strong></p>
   <% @store.files.each do |file| %>
     <% if file.variable? %>
       <%= image_tag file.variant(resize: "200x200") %>
     <% elsif file.previewable? %>
       <%= image_tag file.preview(resize: "200x200"), rails_blob_path(file, disposition: :attachment) %>
     <% else %>
       <%= link_to file.filename, rails_blob_path(file, disposition: :attachment) %>
     <% end %>
   <% end %>
 <% end %>

<br>
<br>
<br>

<%= link_to 'Edit', edit_store_path(@store) %>
<%= link_to 'Back', stores_path %>